# .github/workflows/build.yml
name: Node.js CI

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean install dependencies
        run: yarn install --frozen-lockfile

      - name: Test project
        run: yarn test

      - name: Build project
        run: yarn run build
